Skipping all Posgres test for wallabag:install
We already faced this problem but we are facing it again.
https://github.com/wallabag/wallabag/commit/d502762598db68ec822078642df8f6a8214202f7

It seems we can drop a database properly using wallabag:install.

The server log keep saying:
ERROR:  source database "template1" is being accessed by other users
DETAIL:  There is 1 other session using the database.
STATEMENT:  CREATE DATABASE "wallabag_test"

Which means, it can't remove the database wallabag_test because one other person is using it.